package main

import (
    "fmt"
    "bytes"
)

func build_json(schema string, tenant string, pubkey string) string{
     var buf bytes.Buffer
     buf.WriteString("{")
     buf.WriteString("\"serverState\"")
     buf.WriteString(":")
     buf.WriteString("{")
     buf.WriteString("\"schemaName\"")
     buf.WriteString(":")
     buf.WriteString("\"")
     buf.WriteString(schema)
     buf.WriteString("\"")
     buf.WriteString(",")
     buf.WriteString("\"tenantId\"")
     buf.WriteString(":")
     buf.WriteString("\"")
     buf.WriteString(tenant)
     buf.WriteString("\"")
     buf.WriteString("}")
     buf.WriteString(",")
     buf.WriteString("\"publicKey\"")
     buf.WriteString(":")
     buf.WriteString("\"")
     buf.WriteString(pubkey)
     buf.WriteString("\"")
     buf.WriteString(",")
     buf.WriteString("\"platform\"")
     buf.WriteString(":")
     buf.WriteString("\"Linux\"")
     buf.WriteString(",")
     buf.WriteString("\"deviceId\"")
     buf.WriteString(":")
     buf.WriteString("\"623bce38-a1f4-11e6-bb6c-3417eb9985a6\"")
     buf.WriteString(",")
     buf.WriteString("\"deviceType\"")
     buf.WriteString(":")
     buf.WriteString("\"pc\"")
     buf.WriteString(",")
     buf.WriteString("\"pushToken\"")
     buf.WriteString(":")
     buf.WriteString("\"tt\"")
     buf.WriteString(",")
     buf.WriteString("\"version\"")
     buf.WriteString(":")
     buf.WriteString("\"18.1.2\"")
     buf.WriteString("}")
     fmt.Println(buf.String())
     return buf.String()
}