CC      = gccgo
CFLAGS  = -g
RM      = rm -f
GOPATH  = /usr/local/go/
default: all

#lib_context: 
mkdir -p ../golang.org/x/net/context/_obj/
mkdir -p ../golang.org/x/net
cd /usr/local/go/src/golang.org/x/net/context
all: voc_client_go_app
voc_client_go_app: test_client.go
	$(CC) $(CFLAGS) -o voc_client_go_app test_client.go client_utilities.go

clean veryclean:
	$(RM) voc_client_go_app

